base2/urls.py
from django.urls import path
from .views import index, contato, produto

urlpatterns = [
    path('', index, name='index'),
    path('contato/', contato, name='contato'),
    path('produto/', produto, name='produto'),
]

djangointermediario/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base2.urls')) # Para qualquer rota que não for admin, inclua as rotas da aplicação 'base2' do modulo 'urls.py'
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # Utiliza-se para poder fazer acesso nos templates
# aos arquivos de midia utilizados no uploud

base2/models.py
from django.db import models
from stdimage.models import StdImageField # Importação necessária para se utilizar imagens nos models

# __SIGNALS__: Atua sobre os dados antes de salvar no banco de dados
from django.db.models import signals # 'signals' são utilizados para atuar sobre os models antes ou depois dos dados serem gravados no banco de dados
from django.template.defaultfilters import slugify # 'slugify' utilizado para criar uma slug, isto é, pega o titulo da página e coloca-o separado por traços na url da pagina

class Base(models.Model): # É uma classe abstrata, não criada em banco de dados, e que serve apenas de rascunho para outras classes
    criado = models.DateField('Data de Criação', auto_now_add=True)
    modificado = models.DateField('Data de Atualização', auto_now=True)
    ativo = models.BooleanField('Ativo?', default=True)

    class Meta:
        abstract = True


class Produto(Base):
    nome = models.CharField('Nome', max_length=100)
    preco = models.DecimalField('Preço', max_digits=8, decimal_places=2)
    estoque = models.IntegerField('Estoque')
    imagem = StdImageField('Imagem', upload_to='produtos', variations={'thumb': (124, 124)})
    slug = models.SlugField('Slug', max_length=100, blank=True, editable=False)

    def __str__(self):
        return self.nome

def produto_pre_save(signal, instance, sender, **kwargs):
    instance.slug = slugify(instance.nome)

signals.pre_save.connect(produto_pre_save, sender=Produto)

base2/forms.py
from django import forms # Da framework Django, importa-se o seu proprio modulo de formulários para ser usado
from django.core.mail.message import EmailMessage # Importações necessarias para se utilizar o pacote de emails do django

from .models import Produto


# A classe de formulários raiz do Django é a 'Form', que é definida no modulo 'forms' do Django

class ContatoForm(forms.Form): # Estende Form, logo é uma classe de formulário
    nome = forms.CharField(label='Nome', max_length=100)
    email = forms.EmailField(label='E-mail', max_length=100)
    assunto = forms.CharField(label='Assunto', max_length=120)
    mensagem = forms.CharField(label='Mensagem', widget=forms.Textarea())
    # widget=forms.Textarea() indica que é uma area de texto, portanto deve ser 
    
    def send_mail(self):
        nome = self.cleaned_data['nome']
        email = self.cleaned_data['email']
        assunto = self.cleaned_data['assunto']
        mensagem = self.cleaned_data['mensagem']
        
        conteudo = f'Olá {nome}, responderemos em breve!'

        mail = EmailMessage(
            subject = 'E-mail resposta enviado pelo sistema base2',
            body = conteudo,
            from_email = 'base2@sistemapp.com.br',
            to=[str(email),], # Define para quem o e-mail será respondido
            headers={'replay-to': 'base2@sistemapp.com.br'}
        )
        mail.send()


class ProdutoModelForm(forms.ModelForm): # Estende ModelForm, logo é uma classe de ModelForm
    class Meta:
        model = Produto
        fields = ['nome', 'preco', 'estoque', 'imagem']
    

base2/views.py
from django.shortcuts import render
from django.contrib import messages
from django.shortcuts import redirect

from .forms import ContatoForm, ProdutoModelForm
from .models import Produto

# Create your views here.
# Definiremos três views: A Index que carregará os dados, a pagina de Contatos, e uma view de Formulários

def index(request):
    context = {
        'produtos': Produto.objects.all()
    }
    return render(request, 'index.html', context)


def contato(request):
    form = ContatoForm(request.POST or None)
    if str(request.method) == 'POST':
        # print(f'Post: {request.POST}') # Printa a requisição que foi enviada pelo metodo POST
        if form.is_valid(): # Retorna True se o formulário não tem erros, isto é, se o formulário tem todos os seus campos preenchidos
            form.send_mail() # Envia um e-mail em resposta do usuario que contactou e colocou seus dados no formulário
            messages.success(request, 'Mensagem enviada com sucesso!')
            form = ContatoForm() #Limpando o formulário
        else:
            messages.error(request, 'Erro ao enviar a mensagem')

    context = {
        'form':form
    }
    return render(request, 'contato.html', context)


def produto(request):
    print(f'usuario: {request.user}')
    if str(request.user) != 'AnonymousUser':
        if str(request.method) == 'POST':
            form = ProdutoModelForm(request.POST, request.FILES)
            if form.is_valid():
                prod = form.save(commit=True)
                messages.success(request, f'Produto {prod.nome} salvo com sucesso!')
                form = ProdutoModelForm()
            else:
                messages.error(request, 'Erro ao salvar o produto.')
        else:
            form = ProdutoModelForm()    
        context = {'form':form}
        return render(request, 'produto.html', context)
    else:
        return redirect('index')

base2/templates/contato.html
{% load bootstrap4 %} 
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <title>Contato</title>
    <meta charset="utf-8">
    {% bootstrap_css %}
</head>

<body>
    <div class="container">
        <h1>Contato</h1>
        {% bootstrap_messages %}

        <form action="{% url 'contato' %}" method='POST' class="form" autocomplete="off">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
                <button type="submit" class="btn btn-primary">Enviar</button>
            {% endbuttons %}
        </form>
    </div>
    {% bootstrap_javascript jquery='full' %}
</body>

</html>

base2/templates/index.html
{% load bootstrap4 %}
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <title>Index</title>
    <meta charset="utf-8">
    {% bootstrap_css %}
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">
</head>

<body>

    <div class="container">
        <h1>Prdutos</h1>

        <table class="table">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Nome</th>
                    <th scope="col">Preço</th>
                    <th scope="col">Estoque</th>
                </tr>
            </thead>
            <tbody>
                {% for produto in produtos %}
                    <tr>
                        <td>{{ produto.id }}</td>
                        <th scope="row"><a href="#modal{{ produto.id }}" data-toggle="modal">{{ produto.nome }}</a></th>
                        <td>{{ produto.preco }}</td>
                        <td>{{ produto.estoque }}</td>
                    </tr>
                    <div class="modal fade bd-example-lg show" id="modal{{ produto.id }}" role="dialog">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body" id="dynamic-content">
                                    <img src="{{ produto.imagem.url }}" class="img-fluid" alt="{{ produto.nome }}">
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </tbody>
        </table>   
    </div>

    {% bootstrap_javascript jquery='full' %}
</body>
</html>

base2/templates/produto.html
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <title>Produto</title>
    <meta charset="utf-8">
    {% bootstrap_css %}
</head>

<body>
    <div class="container">
        <h1>Produto</h1>
        {% bootstrap_messages %}

        <form action="{% url 'produto' %}" method='POST' class="form" autocomplete="off" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_nome">Nome</label>
                <input type="text" name="nome" maxlength="100" class="form-control" placeholder="Nome" title="" required="" id="id_nome">
            </div>
            <div class="form-group">
                <label for="id_preco">Preço</label>
                <input type="number" name="preco" step="0.01" class="form-control" placeholder="Preço" title="" required="" id="id_preco">
            </div>
            <div class="form-group">
                <label for="id_estoque">Estoque</label>
                <input type="number" name="estoque" class="form-control" placeholder="Estoque" title="" required="" id="id_estoque">
            </div>
            <div class="form-group">
                <label for="id_imagem">Imagem</label>
                <input type="file" name="imagem" accept="image/*" class="form-control-file" title="" required="" id="id_imagem">
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary">Registrar</button>
            </div>
        </form>
    </div>
    {% bootstrap_javascript jquery='full' %}
</body>
</html>